{combine_css path="themes/default/vendor/fontello/css/gallery-icon.css" order=-10}
{combine_css path="admin/themes/default/fontello/css/fontello.css" order=-11}
{combine_css path="{$TF_PATH}css/tf_identification.css" order=-11}
{combine_css path="admin/themes/default/fontello/css/animation.css" order=10}
{combine_script id='common' load='footer' require='jquery' path='admin/themes/default/js/common.js'}
<script>
  var selected_language = `{$language_options[$current_language]}`;
  var url_logo_light = `{$ROOT_URL}themes/standard_pages/images/piwigo_logo.svg`;
  var url_logo_dark = `{$ROOT_URL}themes/standard_pages/images/piwigo_logo_dark.svg`;
</script>
{combine_script id='standard_pages_js' load='async' require='jquery' path='themes/standard_pages/js/standard_pages.js'}
{combine_script id='tf_identification_js' load='footer' path="{$TF_PATH}js/tf_identification.js"}
{footer_script}
const str_use_app = "{"Enter the verification code generated by your authenticator app"|translate|escape:javascript}";
const str_use_email = "{"Enter the verification code sent to your email address"|translate|escape:javascript}";
const str_err_email = "{"Error when sending email"|translate|escape:javascript}";
const str_email_wait_until = "{"Please wait %s seconds before sending an email again."|translate|escape:javascript}";
const str_send_again_in = "{"Send it again in %s seconds."|translate|escape:javascript}";
let str_handle_error = "{"An error has occured"|translate|escape:javascript}";
{/footer_script}
<container id="mode" class="light">
  <section id="header-options">
    <div>
      <i class="gallery-icon-moon toggle-mode" id="toggle_mode_light" onclick="toggle_mode('dark')"></i>
      <i class="gallery-icon-sun toggle-mode" id="toggle_mode_dark" onclick="toggle_mode('light')"></i>
    </div>
    <div>
      <a href="{$HELP_LINK}" target="_blank">{'Help'|translate}</a>
    </div>
  </section>

  <section id="logo-section">
    <img id="piwigo-logo" src="{$ROOT_URL}themes/standard_pages/images/piwigo_logo.svg">
  </section>

  <section id="tf-form" class="tf profile-section">
    <div class="">
      <h1 class="tf-title-auth">
        {'Two Factor Authentication'|translate}
      </h1>
      <p id="tf_select_desc">{"Select an authentication method."|translate|escape:html}</p>
    </div>

    <div id="tf_select_method">
      <div class="tf-select-method row-flex">
        {if $TF_STATUS_EXTERNAL_APP}
        <div class="tf profile-section column-flex">
          <i class="tf-icon-method gallery-icon-hash"></i>
          <p>{"Authentication app"|translate|escape:html}</p>
          <p class="tf-desc-method">{"Use your external app to authenticate"|translate|escape:html}</p>
          <div class="save">
            <button class="btn btn-main" id="tf_validate_app">{'Validate with app'|translate}</button>
          </div>
        </div>
        {/if}

        {if $TF_STATUS_EMAIL}
        <div class="tf profile-section column-flex">
          <i class="tf-icon-method icon-mail-1"></i>
          <p>{"Email"|translate|escape:html}</p>
          <p class="tf-desc-method">{"Use your email to authenticate"|translate|escape:html}</p>
          <div class="save">
            <button class="btn btn-main row-flex tf-loading-mail" id="tf_validate_email"><i id="tf_loading_email" class="animate-spin icon-spin6"></i>{'Validate with email'|translate}</button>
          </div>
        </div>
        {/if}
      </div>
      <a href="{$TF_LOGOUT}" class="btn btn-cancel tf-logout" id="tf_cancel_auth">{'Cancel'|translate}</a>
    </div>

    <form class="tf-totp-code-verify" id="tf_verify_code" method="post" action="{$F_ACTION}">
      <p id="tf_use_method"></p>
      <div class="otp-container row-flex">
        <div class="input-container">
          <input class="otp-input" id="otp_1" type="number" step="1" min="0" max="9" autocomplete="no" pattern="\d*">
        </div>
        <div class="input-container">
          <input class="otp-input" id="otp_2" type="number" step="1" min="0" max="9" autocomplete="no" pattern="\d*">
        </div>
        <div class="input-container">
          <input class="otp-input" id="otp_3" type="number" step="1" min="0" max="9" autocomplete="no" pattern="\d*">
        </div>
        <div class="input-container">
          <input class="otp-input" id="otp_4" type="number" step="1" min="0" max="9" autocomplete="no" pattern="\d*">
        </div>
        <div class="input-container">
          <input class="otp-input" id="otp_5" type="number" step="1" min="0" max="9" autocomplete="no" pattern="\d*">
        </div>
        <div class="input-container">
          <input class="otp-input" id="otp_6" type="number" step="1" min="0" max="9" autocomplete="no" pattern="\d*">
        </div>
        <input type="hidden" id="full_totp" name="tf_verify_code" />
        <input type="hidden" id="method_totp" name="tf_method_code" />
        <input type="hidden" id="pwg_token" value="{$PWG_TOKEN}" />
      </div>
      <div id="tf_totp_email" class="tf-send-again">
        <p>
            {'You didn’t get the Email?'|translate}
            <span id="tf_send_again" class="tf-underline">{'Send again.'|translate}</span>
            <span id="tf_send_again_in">{'Send it again in %s seconds.'|translate}</span>
          </p>
      </div>
      <div id="tf_totp_external_app" class="">
      </div>
      <div class="save">
        <button type="button" id="tf_go_back" class="tf-btn-simple row-flex"><i class="gallery-icon-left"></i><p>{'Choose another authentication method'|translate|escape:html}</p></button>
        <button type="submit" class="btn btn-main" id="tf_verify">{'Verify'|translate}</button>
      </div>
    </form>
  </section>
  <p class="tf-contact-admin">{"If you are unable to connect, please contact the webmaster"|translate}</p>

  {if count($language_options) > 1}
    <section id="language-switch">
      <div id="lang-select">
        <span id="other-languages">
          {foreach from=$language_options key=$code item=$lang}
            <span id="lang={$code}" onclick="setCookie('lang','{$code}',30)">{$lang}</span>
          {/foreach}
        </span>
        <div id="selected-language-container">
          <i class="gallery-icon-left-chevron"></i><span
            id="selected-language">{$language_options[$current_language]}</span>
        </div>
      </div>
    </section>
  {/if}
  {include file='toaster.tpl'}
</container>