<?php
// +-----------------------------------------------------------------------+
// | This file is part of Piwigo.                                          |
// |                                                                       |
// | For copyright and license information, please view the COPYING.txt    |
// | file that was distributed with this source code.                      |
// +-----------------------------------------------------------------------+
$lang['Too many failed attempts. Please log in again.'] = 'Zbyt wiele nieudanych prób. Proszę zalogować się ponownie.';
$lang['Too many failed attempts. Please try again in %d minutes.'] = 'Zbyt wiele nieudanych prób. Spróbuj ponownie za %d minut.';
$lang['Too many failed attempts. Please try again in %d seconds.'] = 'Zbyt wiele nieudanych prób. Spróbuj ponownie za %d sekund.';
$lang['Two Factor Authentication'] = 'Uwierzytelnianie dwuskładnikowe (2FA)';
$lang['Set up using Email'] = 'Konfiguracja dla poczty e-mail';
$lang['Set up using an authentication app'] = 'Konfiguracja dla aplikacji uwierzytelniającej';
$lang['The 2FA has been successfully deactivated.'] = '2FA zostało pomyślnie dezaktywowane.';
$lang['The code is invalid'] = 'Kod jest nieprawidłowy';
$lang['The code must be in the format: 000000'] = 'Kod musi być w formacie: 000000';
$lang['The email address is missing'] = 'Brak adresu e-mail';
$lang['The recovery codes have been copied.'] = 'Kody odzyskiwania zostały skopiowane.';
$lang['They will not be displayed again.'] = 'Nie będą wyświetlane ponownie.';
$lang['This code will expire in a few minutes for security reasons.'] = 'Ten kod wygaśnie za kilka minut ze względów bezpieczeństwa.';
$lang['To activate the Two Factor Authentication plugin, you need to enable "standard pages" in the Piwigo settings.'] = 'Aby aktywować wtyczkę Two Factor Authentication, musisz włączyć "standardowe strony" w ustawieniach Piwigo.';
$lang['Enter the code'] = 'Wprowadź kod';
$lang['Enter the verification code generated by your authenticator app'] = 'Wprowadź kod weryfikacyjny wygenerowany przez Twoją aplikację uwierzytelniającą';
$lang['Enter the verification code sent to your email address'] = 'Wprowadź kod weryfikacyjny wysłany na Twój adres e-mail';
$lang['Error when sending email'] = 'Błąd podczas wysyłania wiadomości e-mail';
$lang['If you are unable to connect, please contact the webmaster'] = 'Jeśli nie możesz się połączyć, skontaktuj się z administratorem strony';
$lang['If you did not request this setup, please contact your administrator immediately.'] = 'Jeśli nie zażądałeś tego ustawienia, natychmiast skontaktuj się z administratorem.';
$lang['Inactive'] = 'Nieaktywna';
$lang['Invalid recovery code'] = 'Nieprawidłowy kod odzyskiwania';
$lang['Lockout duration in seconds after max attempts (300 = 5 minutes)'] = 'Czas trwania blokady w sekundach po maksymalnej liczbie prób (300 = 5 minut)';
$lang['Maximum number of failed attempts before lockout'] = 'Maksymalna liczba nieudanych prób przed zablokowaniem';
$lang['Please add an email first before activating two factor authentication by email.'] = 'Proszę dodać adres e-mail przed aktywacją uwierzytelniania dwuskładnikowego przez e-mail.';
$lang['Please enable at least one authentication method in the plugin configuration.'] = 'Proszę włączyć co najmniej jedną metodę uwierzytelniania w konfiguracji wtyczki.';
$lang['Please wait %s seconds before sending an email again.'] = 'Poczekaj %s sekund przed ponownym wysłaniem wiadomości e-mail.';
$lang['Recommanded'] = 'Zalecana';
$lang['Save your recovery codes in a safe place'] = 'Zapisz swoje kody odzyskiwania w bezpiecznym miejscu';
$lang['Scan the QR code'] = 'Zeskanuj kod QR';
$lang['Select an authentication method.'] = 'Wybierz metodę uwierzytelniania.';
$lang['Send again.'] = 'Wyślij ponownie.';
$lang['Send email'] = 'Wyślij e-mail';
$lang['Send it again in %s seconds.'] = 'Wyślij ponownie za %s sekund.';
$lang['2FA by application'] = '2FA przez aplikację';
$lang['2FA by email'] = '2FA przez e-mail';
$lang['Active'] = 'Aktywna';
$lang['Auth app'] = 'Aplikacje uwierzytelniające i rozszerzenia przeglądarki, takie jak 1Password, Authy, Microsoft Authenticator itp., generują jednorazowe hasła, które są używane jako drugi składnik weryfikacji Twojej tożsamości po wyświetleniu monitu podczas logowania.';
$lang['Authentication app'] = 'Aplikacja uwierzytelniania';
$lang['Can\'t connect? <u>Use a recovery code.</u>'] = 'Nie możesz się połączyć? <u>Użyj kodu odzyskiwania.</u>';
$lang['Choose another authentication method'] = 'Wybierz inną metodę uwierzytelniania';
$lang['Configure your two-factor authentication settings and secure your acount'] = 'Skonfiguruj ustawienia uwierzytelniania dwuskładnikowego i zabezpiecz swoje konto';
$lang['Confirm your email'] = 'Potwierdź swój adres e-mail';
$lang['Deactivated for next connection'] = 'Dezaktywowane dla następnego połączenia';
$lang['Disable 2FA authentication'] = 'Wyłącz uwierzytelnianie 2FA';
$lang['Disable 2FA authentication for next connection'] = 'Wyłącz uwierzytelnianie 2FA dla następnego połączenia';
$lang['Disable in plugin configuration'] = 'Wyłącz w konfiguracji wtyczki';
$lang['Do you really want to disable two factor authentication by application?'] = 'Czy na pewno chcesz wyłączyć uwierzytelnianie dwuskładnikowe przez aplikację?';
$lang['Do you really want to disable two factor authentication by email?'] = 'Czy na pewno chcesz wyłączyć uwierzytelnianie dwuskładnikowe przez e-mail?';
$lang['Email two-factor authentication has been successfully enabled'] = 'Uwierzytelnianie dwuskładnikowe przez e-mail zostało pomyślnie włączone';
$lang['Emails don\'t match'] = 'Adresy e-mail różnią się';
$lang['Enable 2FA by application'] = 'Włącz 2FA przez aplikację';
$lang['Enable 2FA by email'] = 'Enable 2FA by email';
$lang['Enter one of your recovery codes'] = 'Wprowadź jeden ze swoich kodów odzyskiwania';